### ISSUE TITLE
org.grails.plugins:mongodb:7.0.0 has dependency on nonexistent grails-bom:4.0.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by yuhuawang2** [grails/gorm-mongodb#103]
I am creating a Grails 4 project that uses MongoDB and I have added:
 
`compile "org.grails.plugins:mongodb:7.0.0"` to my build.gradle's dependencies section.

However when I try to run my application, I get the following error:

```
Could not resolve org.grails.plugins:mongodb:7.0.0.
Could not parse POM https://artifacts.x.com/libs-release/org/grails/plugins/mongodb/7.0.0/mongodb-7.0.0.pom
Could not find org.grails:grails-bom:4.0.0.BUILD-SNAPSHOT.
```

Looking at mongodb-7.0.0.pom, I see that it has a dependency on grails-bom:4.0.0.BUILD-SNAPSHOT, which is no longer available in the artifacts repository as it has been replaced by grails-bom:4.0.0. In this case, how can I get past this missing dependency error?

I have been trying to override the grails-bom dependency by adding things like:

```
compile ("org.grails.plugins:mongodb:7.0.0") {
        exclude group: 'org.grails', module: 'grails-bom'
    }
    implementation(platform("org.grails:grails-bom:4.0.0"))
```

but so far nothing seems to work.

Thanks in advance for your help!

**Comment by puneetbehl** [comment]
@yuhuawang2 I am able to use GORM for MongoDB 7.0.0. Could you please share a sample application?

**Comment by puneetbehl** [comment]
Closed due to lack of feedback
