### ISSUE TITLE
Not able to set expireAfterSeconds property on mongo collection index

### ISSUE THREAD

**Issue by sryara** [grails/gorm-mongodb#114]
I am trying to create a **TTL** on a mongo collection and try to create index and set `expireAfterSeconds`. After doing some painful debugging I found I have to set it through `expireAfter(java.lang.Long expireAfter, java.util.concurrent.TimeUnit timeUnit)` method.

my code in the entity is like below

```
static mapping = {
  timeToLive index: true indexOptions:[expireAfter:[60, TimeUnit.SECONDS]]
}
```

and set is done via [MongoConstants#mapToObject](https://gorm.grails.org/latest/mongodb/api/org/grails/datastore/mapping/mongo/MongoConstants.html) method and this give me an exception. How can I set values to `expireAfter` method?

**Comment by sryara** [comment]
@graemerocher Can you please let me know if there any alternative for this. I am not able to find any examples of this online.

**Comment by eyalge** [comment]
Setting the value as Long (e.g. 60L) did the trick for me

**Comment by sryara** [comment]
@eyalge Do you mean 

```
static mapping = {
  timeToLive index: true indexOptions:[expireAfter:[60L, TimeUnit.SECONDS]]
}
```
??

Can you please post your particular block of code or elaborate on your comments?

**Comment by eyalge** [comment]
Hi @sryara , 
yes that is what I meant, but I used a different syntax for creating the index:
`
...
static mapping = {
        index([dateDeleted: 1], [background: true, expireAfter: [60L, TimeUnit.MINUTES], name: "deletedTTL"])
    }
...
`

in my case I have a `dateDelete` field of type `java.util.Date` which I want to expire after 60 minutes from the date value set to this field.

Hope it helps.

**Comment by sryara** [comment]
@eyalge Working like a charm. Thank you very much. Too bad I had to scour through source code to figure out `expireAfter`. Not a fan of grails at all.
