### ISSUE TITLE
Fields inherited from abstract class are never dirty

### ISSUE THREAD

**Issue by mugren** [grails/gorm-mongodb#12]
When domain class is mapped with mongo and extends from abstract class, then the fields defined in the abstract class are never marked as dirty when their value is changed.

Example: https://github.com/mugren/abstract-dirty-vanilla

Aside that after calling save on the domain object the method domainObject.getDirtyPropertyNames() includes the className of the instance as list item too. 

Edit: tested with mongodb:5.0.10 version of the plugin

**Comment by graemerocher** [comment]
The `className` issue has been fixed already. As for this issue you would need mark your abstract parent call with the `@DirtyCheckable` transformation, otherwise we cannot detect changes you make to the parent properties

**Comment by mugren** [comment]
@graemerocher thanks for the provided solution, it works now.
