### ISSUE TITLE
Mongo's criteria does not have a 3 arg eq() method

### ISSUE THREAD

**Issue by erichelgeson** [grails/gorm-mongodb#19]
``` groovy
Book.createCriteria.get {
    eq("title", "THE STAND", [ignoreCase: true])
}
```

Will fail if using GORM with mongo, though works with hibernate. I'm not sure how the hibernate options would/could map to mongo.

See also https://github.com/grails-plugins/grails-spring-security-core/pull/450#issuecomment-252039095

**Comment by puneetbehl** [comment]
I believe it will be converted into regex query for MongoDB, something similar to following:

```bash
db.stuff.find( { foo: /^bar$/i } );
```

However, I am not sure about the support of `eq` with `params` in case of MongoDB. One can do something similar to above to achieve case insensitive comparison.

**Comment by erichelgeson** [comment]
Yes, it is easy to work around, I was only highlighting the difference in api while implementing that feature in ssc.

You added the Awaiting Feedback but I have no feedback to give, I don't use mongodb. Feel free to do with this issue what you see fit.

**Comment by mishrarahulranjan** [comment]
how to hook custom gorminstance api in grail 3.x, gorm 6.x

below link is not working.

http://www.tothenew.com/blog/hooking-into-the-instance-methods-of-the-gorm-api/

gorm decorator groovy.lang.MissingMethodException: No signature of method:
com.test.domain.UserInbox.currentGormInstanceApi() is applicable for
argument types: () values: []
