### ISSUE TITLE
Grails 2.5.6, Hibernate 4, and MongoDB 6 App Compile Error

### ISSUE THREAD

**Issue by tonymorell10** [grails/gorm-mongodb#204]
I have a legacy Grails 2.5.6 application that uses the hibernate 4 and mongodb plugins, (6.1.2).
The application used to compile fine, but now I get this error when attempting to build a war file.

Loading Grails 2.5.6
|Configuring classpath
.
|Environment set to test
.................................
|Packaging Grails application
.....Error 
|
Fatal error during compilation java.lang.NoClassDefFoundError: grails/persistence/support/PersistenceContextInterceptor (Use --stacktrace to see the full trace)
Error |
org.codehaus.groovy.grails.cli.ScriptExitException
Error |
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Error |
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
Error |
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Error |
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
. . .

Here's a snippet from BuildConfig.groovy

`dependencies {
        // specify dependencies here under either 'build', 'compile', 'runtime', 'test' or 'provided' scopes e.g.
        // runtime 'mysql:mysql-connector-java:5.1.29'
        // runtime 'org.postgresql:postgresql:9.3-1101-jdbc41'
        test "org.grails:grails-datastore-test-support:1.0-grails-2.4"
		//	compile 'commons-beanutils:commons-beanutils:1.8.3' // added for export:1.6 plug in
		
		compile 'org.springframework:spring-tx:4.2.0.RELEASE'
		compile 'org.springframework:spring-context:4.2.0.RELEASE'
		compile 'org.springframework:spring-beans:4.2.0.RELEASE'
		compile 'org.springframework:spring-core:4.2.0.RELEASE'
		compile 'org.springframework:spring-expression:4.2.0.RELEASE'
	
    }

    plugins {
        // plugins for the build system only
        //  build ":tomcat:7.0.54"
		//build ':tomcat:7.0.55.2'
		build ':tomcat:7.0.70'

        // plugins for the compile step
        compile ":scaffolding:2.1.2"
       // compile ':cache:1.1.7'
		compile ':cache:1.1.8'
      //  compile ":asset-pipeline:1.8.11"
		//compile ':asset-pipeline:2.1.5'
		//compile ':asset-pipeline:1.9.9'
		compile ":asset-pipeline:2.5.7"

        // plugins needed at runtime but not for compilation
     //   runtime ":hibernate4:4.3.5.4" // or ":hibernate:3.6.10.16"
		//runtime ':hibernate4:4.3.8.1'
        runtime ":database-migration:1.4.0"
        runtime ":jquery:1.11.1"

        // Uncomment these to enable additional asset-pipeline capabilities
        //compile ":sass-asset-pipeline:1.7.4"
        //compile ":less-asset-pipeline:1.7.0"
        //compile ":coffee-asset-pipeline:1.7.0"
        //compile ":handlebars-asset-pipeline:1.3.0.3"
		
		compile (":hibernate4:6.1.2") {
			excludes 'grails-datastore-simple'
		}
		
		compile ':spring-security-core:2.0-RC4' // spring security core
		compile ':spring-security-ldap:2.0-RC2' // spring security ldap
		compile ":quartz:1.0.2"
		compile ":quartz-monitor:1.0"
		//compile ":export:1.6"
		//compile ':mongodb:3.0.3'
		compile ":mongodb:6.1.2"
		
    }`

**Comment by jameskleeh** [comment]
Grails 2 has been end of lifed
