### ISSUE TITLE
Grails 3.1.12 and mongodb 6.0.3 Configuration Error

### ISSUE THREAD

**Issue by barcelona23** [grails/gorm-mongodb#29]
I'm trying to config mongodb 6.0.3 to my current app but I'm getting this error.
I'm using only mongodb as database, so I just commented all about hibernate.

Do I have some missing config? 
Thanks in advance.

`java.lang.NoClassDefFoundError: org/grails/datastore/gorm/plugin/support/ConfigSupport`
 
error

![screen shot 2016-11-05 at 3 46 32 pm](https://cloud.githubusercontent.com/assets/221474/20033826/b88d1680-a36f-11e6-99ab-f1a463a1a36a.png)

build.gradle

![screen shot 2016-11-05 at 3 47 45 pm](https://cloud.githubusercontent.com/assets/221474/20033819/9e0fe922-a36f-11e6-87da-58c14c08fa00.png)

application.yml

![screen shot 2016-11-05 at 3 48 29 pm](https://cloud.githubusercontent.com/assets/221474/20033823/ad52d480-a36f-11e6-846c-ec4f8c1f8318.png)

**Comment by graemerocher** [comment]
Try force the GORM version to 6.0.3 as per http://gorm.grails.org/latest/hibernate/manual/index.html#gettingStarted

**Comment by barcelona23** [comment]
It works!!! 
thank you.
