### ISSUE TITLE
No effect on setting failOnError in application.yml with MONGO DB plugin 6.0.4

### ISSUE THREAD

**Issue by dreampursuer** [grails/gorm-mongodb#30]
I have grails app created using 3.2.3 MongoDB plugin 6.0.4 without Hibernate plugin.
I use the following setting in application.yml for mongodb:

grails:
    gorm:
        failOnError: true

---

grails:
    mongodb:
        host: "xxx"
        port: 27017
        databaseName: "xxx"

---
There's no exception thrown when call domainInstance.save() on bad data.
But it works fine on calling domainInstance.save(failOnError:true).

This bug has been fixed in MONGO DB plugin 5.0.9, but it reproduced now.
The related bug is https://github.com/grails/grails-data-mapping/issues/734.

**Comment by graemerocher** [comment]
I added a functional test (see above) and cannot reproduce the problem. Please try 6.0.5 otherwise provide an example that reproduces the problem
