### ISSUE TITLE
multi tenancy with mongodb not updating version column of domain class

### ISSUE THREAD

**Issue by zohaibj** [grails/gorm-mongodb#31]
Using multi tenant approach at database level. Domain classes gets saved correctly in respective tenant databases however for these domain classes version column is not saved. Which means optimistic lock exception is thrown when such an object is updated. 

[Sample project to reproduce scenario](https://github.com/z-j/grails-exp/tree/master/MongoMultiTenancyTest)

[StackOverflow Question](http://stackoverflow.com/questions/41039397/multi-tenancy-with-mongodb-not-updating-version-column-of-domain-class)

Grails Version: 3.0.1
Groovy Version: 2.4.3
JVM Version: 1.8.0_31
'org.grails.plugins:mongodb:6.0.4'

Details:
Domain class which implements "MongoEntity<Book>, MultiTenant<Book>" traits, when such a domain class is saved as:

Tenants.withCurrent {
                book.save(flush: true)
            }

then version column is not saved. Version column gets saved if we remove the " implemetns MongoEntity<Book>, MultiTenant<Book>" from domain class, but then class gets saved in default database and not the tenant one. Highly appreciate your help.

**Comment by graemerocher** [comment]
Thanks for the report. In the meantime I recommend disabling optimistic locking for your entities with

static mapping = { 
     version false
}
