### ISSUE TITLE
<Class>.list method does not return the correct class objects for MongoDB

### ISSUE THREAD

**Issue by tatleung** [grails/gorm-mongodb#33]
For inheritance class hierarchy object mapping, calling the list() method in the base class is returning objects from the derived classes as well as the base class.  For example, if Pet is the base class and Cat and Dog extends Pet, calling Pet.list() is returning objects created from the Cat and Dog classes.

Please see the following Github repository to reproduce the problem:  https://github.com/tatleung/gorm-inheritance-test

There are 2 branches in the repository: the mongodb branch will help reproduce the problem.  The mysql branch verifies the same use case is working correctly in MySQL.

**Comment by graemerocher** [comment]
That is the correct behaviour and it is working as designed
