### ISSUE TITLE
Unsetting (nulling out) a domain property value is missed by PersistentEntityCodec

### ISSUE THREAD

**Issue by gorgiev** [grails/gorm-mongodb#36]
Discovered in Grails 3.2.5 - Gorm 6.0.6

Assigning a property of a persisted domain instance to null and saving the instance results in the old (non-null) value retained in the data store. 

This is caused by the check condition at line 263 in PersistentEntityCodec only collecting unset operations for embedded domain types.   

Here is a test case to replicate the issue. Add to DirtyCheckUpdateSpec suite add:

    void "Test unsetting a property through dirty check"() {
        given:"A domain instance"
        def b = new Bar(foo:"stuff")
        b.save(flush:true)
        session.clear()

        when:"The domain is updated with a null property value"
        b = Bar.get(b.id)
        b.foo == 'stuff'

        b.setProperty('foo', null)
        b.isDirty()
        b.isDirty('foo')
        b.save(flush:true)
        session.clear()
        b = Bar.get(b.id)

        then:"the update did unset the nulled property"
        b.foo == null
        b instanceof DirtyCheckable
    }

The test fails with an unsatisfied condition:

Condition not satisfied:
b.foo == null
| |   |
| |   false
| stuff
org.grails.datastore.gorm.mongo.Bar : 589a4089bcb2a66b00f802d9

NOTE: It appears the same issue is present in the BsonPersistentEntityCodec (line 256).

I believe this is a serious issue as it prevents from resetting domain properties on update.

**Comment by gorgiev** [comment]
An update on this that will help. I see there is an equivalent test case already, named NullsAreNotStoredSpec. However, this test passes validate:false to the update save() call (line 43).

If that parameter is removed leaving only the flush:true, then the test will fail at line 49. The personObj.name will retain its "John Smith" value. 

So the validation does something that breaks the null assignment.

**Comment by graemerocher** [comment]
@gorgiev Thanks for the reports, we will take a look soon. In the meantime pull requests welcome!

**Comment by jameskleeh** [comment]
@gorgiev In that case foo is `nullable: false` so it should fail validation, which would cause the change to not persist
