### ISSUE TITLE
Transaction across multiple services does not roll back on RuntimeException

### ISSUE THREAD

**Issue by bleurubin** [grails/gorm-mongodb#40]
When an error occurs within a transaction that spans multiple services, saves that occur prior to the error are not rolled back.  The saves are not flushing the transaction.  It looks like Transactions aren't explicitly supported in mongo, if this is expected behavior maybe it should be called out in the documentation:

http://gorm.grails.org/latest/mongodb/manual/index.html#transactions

I also tried it across multiple services with the same type of domain object and behavior was the same.

mongo test showing the issue: https://github.com/bleurubin/testapp/tree/mongo-transactions-bug

failing test: https://github.com/bleurubin/testapp/blob/mongo-transactions-bug/src/integration-test/groovy/FooBarServiceIntegrationSpec.groovy#L83

hibernate test that correctly rolls back the transaction: https://github.com/bleurubin/testapp/tree/hibernate-transactions-1

**Comment by graemerocher** [comment]
MongoDB does not support transactions so this is expected behaviour

**Comment by dreampursuer** [comment]
MongoDB 4.0 supports Multi-Document ACID Transaction now.

**Comment by graemerocher** [comment]
Indeed, we will investigate adding support for that
