### ISSUE TITLE
RestfulController stops rendering on index() for some reason (related to mongo)

### ISSUE THREAD

**Issue by jakecoffman** [grails/gorm-mongodb#45]
Bug reproducible here: https://github.com/jakecoffman/grails3-mongo-bug

The project inserts two Authors in the Bootstrap, but if you hit `/authors` only 1 is listed. 

It has something to do with storing a list of strings inside of a Map on the domain. If you create Authors that don't put Lists in Maps then they all render just fine. 

I have reproduced this under grails 2 as well.

**Comment by jakecoffman** [comment]
I updated the example and added another similar but different bug. The Bacon (`/bacon`) domain only renders 1 item when you list them, but in this case it's not because of a domain property, but I made a custom marshaller that renders an empty list: https://github.com/jakecoffman/grails3-mongo-bug/blob/master/grails-app/init/grails3/mongo/bug/BootStrap.groovy#L18

**Comment by jakecoffman** [comment]
Any idea when a build might be produced with this fix @graemerocher?

**Comment by graemerocher** [comment]
new GORM releases will be out on the next few days

**Comment by graemerocher** [comment]
btw you can workaround it by calling `size()` on the returned list before rendering it
