### ISSUE TITLE
change to a property from within class is not updated to db during update

### ISSUE THREAD

**Issue by snimavat** [grails/gorm-mongodb#49]
When a property is changed from within class: eg during beforeValidate().
The updated value will not be saved to db unless I explicitely mark the property as dirty or call the setter method on property rather then direct assignment

Example:

```
class Test {
	static mapWith = "mongo"

	String value
	String computed

	static constraints = {
		value nullable: false
		computed nullable: true
	}

	def beforeValidate() {
		if(id == null || isDirty("value")) computed = value + "-computed"
                //markDirty("computed") or setComputed(xxx) will work.
	}

}
```

In above example: when i do
```
Test test = Test.findByValue(""xxx")
test.value = "new-value"
test.save()
```

The beforeValidate will be called, the computed property will change, but the changed value will not be persisted to collection.

I guess this has some thing to do with how grails tracks the dirty properties. As this thing works fine with hibernate, i would expect it to work with gorm for mongo too.

Note: This thing does not reproduce in integration tests, you have to do run-app or write a functional test.

**Comment by graemerocher** [comment]
Calling `markDirty("..")` is the correct thing to do.
