### ISSUE TITLE
Can't find a codec for class java.math.BigDecimal

### ISSUE THREAD

**Issue by sadasivaiahgoli** [grails/gorm-mongodb#52]
I am using grails 3.2.9 and gormMongo version 6.1.2 and mongo driver 3.1.2. Mongo db server version 3.4.7.  when I insert the 
documents in low level by using doc.put('price',new BigDecimal(value)). while saving It throw the exception .
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class java.math.BigDecimal

**Comment by graemerocher** [comment]
Upgrade to mongo driver 3.4.2

**Comment by sadasivaiahgoli** [comment]
Iam using mongo driver 3.4.2

**Comment by graemerocher** [comment]
Then this a driver issue not a GORM issue. Looking at the driver code there is no `BigDecimalCodec` you have to use the `Decimal128` type when working with the driver APIs directly. See http://mongodb.github.io/mongo-java-driver/3.4/javadoc/org/bson/types/Decimal128.html#Decimal128-java.math.BigDecimal-

You can report issues with the driver here https://jira.mongodb.org/projects/JAVA
