### ISSUE TITLE
Index is not created in multitenant schema mode

### ISSUE THREAD

**Issue by patrikeev** [grails/gorm-mongodb#53]
When using the code below the index is not created:

```
class Person implements MultiTenant<Person> {
    String name
    static mapping = {
        name index:true
    }
}
```

**Comment by patrikeev** [comment]
Latest version of GORM/Grails

**Comment by puneetbehl** [comment]
It is working fine with following:
```
grailsVersion=3.3.2
gormVersion=6.1.8.RELEASE
gradleWrapperVersion=3.5
```

Could you please upload the example?

**Comment by puneetbehl** [comment]
This seems like by design, look [here](https://github.com/grails/gorm-mongodb/blob/master/grails-datastore-gorm-mongodb/src/main/groovy/org/grails/datastore/mapping/mongo/MongoDatastore.java#L514)
