### ISSUE TITLE
Why DomainClass.find() not working on map attribute

### ISSUE THREAD

**Issue by sadasivaiahgoli** [grails/gorm-mongodb#55]
Iam using grails 3.2.9 and gorm mongodb plugin 6.1.2 and mongo driver 3.4.2

```
@GrailsCompileStatic
class GrowthAnalysis {


    ObjectId id
   String symbol
    Date lastUpdated
    List<HistoricalData> historicalData
    Long updatedYear
    PEData peData
    static embedded = ['historicalData','peData']

    static constraints = {
        peData(nullable:true)
    }

}
@GrailsCompileStatic
class PEData {
    ObjectId id
    Map<String,BigDecimal> growthInBookValue
 
    static constraints = {
        growthInBookValue(nullable:true)
        
    }
    static embedded = ['growthInBookValue']

```
when I save growthAnalysis on gorm save method it will save perfetcly.
while retriving growthAnaysis object by find () method
```
 def  ga = GrowthAnalysis.findBySymbol(symbol)
it will throw the exception 
Caused by: java.util.NoSuchElementException: Cannot access first() element from an empty List
```

**Comment by graemerocher** [comment]
Provide an example that reproduces the issue.

**Comment by puneetbehl** [comment]
@sadasivaiahgoli It seems like it's working fine and is related to your specific configuration. Please look into the [puneetbehl/gm-issues#55](https://github.com/puneetbehl/gm-issue-55) for reference and let me know if you still see issues by sending PR to replicate the problem.
