### ISSUE TITLE
Exception when using Decimal128

### ISSUE THREAD

**Issue by miguelabautista** [grails/gorm-mongodb#56]
```
class RuleBase {
    String ruleBaseName
    Decimal128 deMinimusValueInsured
    Decimal128 deMinimusValueUninsured
    Decimal128 manualReviewLimit
}
```
I am trying to use `Decimal128` instead of `BigDecimal` but I am getting this exception when calling `RuleBase.list()` of any other query. No errors when saving.

```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.bson.types.Decimal128]
```
If I look into mongo I see that the `Decimal128` properties are saved as `String`.

**Comment by graemerocher** [comment]
You can use `BigDecimal` types instead. They will be converted to and from `Decimal128`

**Comment by miguelabautista** [comment]
the problem is that I have a problem using BigDecimal with latest version. I migrated the project from 3.2.9 (everything works with that version). 

the error is very strange because in some pcs there are no errors but in others I get this exception.

com.mongodb.MongoSocketReadException: Prematurely reached end of stream.

**Comment by graemerocher** [comment]
that error normally indicates you are using a version of MongoDB that doesn't support Decimal128

**Comment by amarchen** [comment]
I had very similar issue lately when upgrading Grails from 3.2 to 3.3 (AKA upgrading GORM from 6.0 to 6.1) with MongoDB 3.2. Have a look at the MongoDB server logs if you can access these. We had the following there:
```
Attempt to use a decimal BSON type when experimental decimal server support is not currently enabled.
```

It seems that GORM 6.0 autoconverted decimals to String while GORM 6.1 (and java driver 3.4 underneath) assume that MongoDB is supporting Decimal128 and use it while MongoDB 3.2 doesn't fully support Decimal128 yet. Fortunately, [there is a non-document setting in grails/gorm that lets you disable Decimal128 use](https://www.agilesoftwaredevelopment.com/posts/gorm-mongodb-decimal-type/) - just put `grails.mongodb.decimalType: false` to your `application.yml`
