### ISSUE TITLE
Documentation- datasource-simple mitigation in Grails 2.x 

### ISSUE THREAD

**Issue by nialloconnor** [grails/gorm-mongodb#57]
In the documentation for the latest version of the plugin 6.1.4 there is a section on how the datasource-simple dependency has been removed. There are instructions for Grails 3.x on how to handle this (http://gorm.grails.org/latest/mongodb/manual/#upgradeNotes)  but there isn't the equivalent for Grails 2.x

**Comment by puneetbehl** [comment]
I think you can exclude the datastore-simple dependency in Grails 2 as following:
a) Exclude Grails global dependency
```groovy
...

grails.project.dependency.resolution = {
	// inherit Grails' default dependencies
	inherits("global") {
		// specify dependency exclusions here; for example, uncomment this to disable ehcache:
		// excludes 'ehcache'
		excludes "grails-datastore-simple"
	}

...
```

b) Excluding from MongoDB plugin:
```groovy
...

plugins {
		// plugins for the build system only
		build ":tomcat:7.0.55.3" // or ":tomcat:8.0.22"

		compile ":quartz:1.0.2"
		compile (":mongodb:5.0.5.RELEASE") {
			excludes "grails-datastore-simple"
		}

...
```

**Comment by puneetbehl** [comment]
Closed due to lack of feedback.
