### ISSUE TITLE
Very frequent Optimistic Locking exception

### ISSUE THREAD

**Issue by ChiranjibKarn** [grails/gorm-mongodb#64]
We are using Grails 3.2.11 with mongodb (GORM version 6.0.12.RELEASE) in our REST application. MongoDB version is 3.4.
The problem is we are getting Optimistic Locking very frequently and since we are not able to replicate it in our local and staging environment it is very hard to debug the issue.
In our production environment, it throws Optimistic locking with HTTP Status 500 which eventually crashes our backend.
I saw it has been fixed and closed in [https://github.com/grails/grails-data-mapping/issues/180](url), but am not sure whether the issue has been resurfaced or what?
If not, then what would be the better way to handle this exception?

**Comment by graemerocher** [comment]
You receive it production because you are getting concurrent updates that could lead to lost writes. You can either disable optimistic locking:

```
static mapping = { version false }
```

Or catch the exception and retry the update.

**Comment by ChiranjibKarn** [comment]
Thanks for your reply @graemerocher . 
I do not like the idea of disabling version, that way you will be losing updates by simply overwriting it.
Yes, we are catching exception and increment version number manually, even in this case I doubt am losing updates and forcing GORM to persist only my updates.
Can't GORM handle this situation by doing `refresh` on the domain object internally? Or can't it `merge` the dirty properties by itself before persisting it?

**Comment by graemerocher** [comment]
Nope it cannot since the best way to handle the error is application specific and we cannot make the decision whether losing updates is ok for users

**Comment by ChiranjibKarn** [comment]
Thank you for the suggestion, we will take care of it within the application.
