### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by davidboutet** [grails/gorm-mongodb#657]
Hello, where is the documentation for this plugin?

This page seem to have issues: https://gorm.grails.org/latest/mongodb/manual/index.html

Can you please fix it or give me the new link for the documentation

Thanks

**Comment by matrei** [comment]
@puneetbehl Can you republish docs now after #656 has been applied

**Comment by davidboutet** [comment]
#650 is closed and #656 is merged but documentation is still missing..
