### ISSUE TITLE
optimistic locking exception in case of multiple user in grails 2.5.4 with mongo db

### ISSUE THREAD

**Issue by mishrarahulranjan** [grails/gorm-mongodb#68]
controller -> service
we are manipulating the domain object in a service . For single user it is working fine.
for multiple user, it throws optimistic locking exception. Even after synchronizing the access of shared object between threads,getting Optimistic Locking very frequently.

what is way to handle this exception.

**Comment by graemerocher** [comment]
Duplicates #64

**Comment by vivekbdh** [comment]
I think the following issue is related...
https://stackoverflow.com/questions/52696721/how-to-update-record-using-grails-application-that-inserted-by-rest-webservice
