### ISSUE TITLE
When stateless and self-assigned identifiers are used, updates are not detected

### ISSUE THREAD

**Issue by alvarosanchez** [grails/gorm-mongodb#70]
Given a domain class with this mapping:

```groovy
static mapping = {
    id generator:'assigned'
    stateless true
}
```

When using `save()` to update an existing instance, GORM tries to do an insert, and the operation fails because of a duplicate key.

The branch `stateless_and_self_assigned_id` has a test that reproduces the issue.

**Comment by puneetbehl** [comment]
@alvarosanchez please check out now with 6.1.6.BUILD-SNAPSHOT.

**Comment by alvarosanchez** [comment]
@puneetbehl did you mean `6.1.10.BUILD-SNAPSHOT`? Also, this issue's milestone is wrong

**Comment by alvarosanchez** [comment]
My mistake, this plugin's version is different from GORM's
