### ISSUE TITLE
Support for MongoDB 3.6

### ISSUE THREAD

**Issue by caleb1993** [grails/gorm-mongodb#73]
Does this plugin support MongoDB 3.6?

From what I can tell it is not using the 3.6 java driver which is the only java driver supported for MongoDB 3.6 according to this compatibility reference.
https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#java-driver-compatibility

**Comment by ajayshah1992** [comment]
Yes, this update will help to latest feature of mongo db.

**Comment by smakela** [comment]
Atleast if you check the documentation of the javadrivers 3.6 driver should be source and binary compatible with 3.5 and 3.4 driver versions. 3.4 driver introduced some breaking changes but those are already done in the current gorm-mongodb plugin.

I would just update the java driver and test the app with it.

**Comment by ajayshah1992** [comment]
Yes, I could not able to use filterarray with 3.4 java driver. Yes please steps to update this java driver to 3.6.

**Comment by puneetbehl** [comment]
You can update the driver version to 3.6 in the `build.gradle` under the `dependencies` block as:

```
compile "org.mongodb:mongodb-driver:3.6.4"
```
