### ISSUE TITLE
Tests using Java 8 Temporal classes in queries don't work

### ISSUE THREAD

**Issue by MitchJust** [grails/gorm-mongodb#95]
In grails 3 and 4 it seems that trying to use the Java 8 temporal classes (LocalDate, Instant etc.) does not work correctly in queries in tests.

We found a workaround for Grails 3 to manually set up the codecs as a Spock extension:
```
import groovy.util.logging.Slf4j
import org.grails.plugins.bson.CodecRegistry
import org.spockframework.runtime.extension.AbstractGlobalExtension
import org.spockframework.runtime.model.SpecInfo

/**
 * grails-java8 codecs aren't registered during tests, so explicitly add them
 */
@Slf4j
class Java8CodecExtension extends AbstractGlobalExtension {
    @Override
    void visitSpec(SpecInfo specInfo) {

        specInfo.addSetupSpecInterceptor({ invocation ->

            log.info("Applying Java8 Codecs")
            CodecRegistry.registerDecoders()
            CodecRegistry.registerEncoders()

            invocation.proceed()
        })
    }
}
```

but now that the java-8 plugin has been removed from Grails 4, this workaround is no longer valid.

See https://github.com/MitchJust/mongo-testing-java8/ for examples of tests failing using:
- GORM dynamic finders
- `.find(Bson ...)`
- Aggregate Pipelines

_only_ when using a LocalDate, Instant etc.

**Comment by jameskleeh** [comment]
@MitchJust Are you sure the behavior is limited to tests? I created a simple controller in the app and it appears that its not working during normal execution

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/gorm-mongodb/commit/a45f6eed9bf0be82c89952c750bf5ad070017d57

**Comment by MitchJust** [comment]
Thanks @jameskleeh

I didn't actually get a chance to test this in a running app, in Grails 3 the issue definitely only presented in tests, but worked fine while running.

Apologies for not having raised the issue back then.
